name: Hugo Build CI

on:
  push:
    branches:
    - 'main'
    - 'master'
    - 'staging'
  workflow_dispatch:

jobs:
    #Broken Link Checker using Broken Link Checker Action provided by technote-space
  # -exclude excludes any vpn links or links that are prone to false negatives
  Broken_Link_Checker:
    name: Broken Link Check
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Set URL based on branch
        id: set-url
        run: |
          #if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          #  echo "URL=https://rc.virginia.edu" >> $GITHUB_ENV
          #elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
          echo "URL=https://staging.rc.virginia.edu" >> $GITHUB_ENV
          #else
          #  echo "URL=https://staging.rc.virginia.edu" >> $GITHUB_ENV
          #fi

      - name: Run Broken Link Checker
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: ${{ env.URL }}
          cmd_params: 
            --buffer-size=8192
            --max-connections=10
            --max-connections-per-host=1
            --rate-limit=5                   
            --accepted-status-codes=200..300,301,403,406,999,429
            --skip-tls-verification
            --timeout=60
            --exclude="(https://xdmod2.hpc.virginia.edu|https://groups.identity.virginia.edu|https://fastx.hpc.virginia.edu|https://uvarc.io/support|https://services.rc.virginia.edu/|https://mygroups.virginia.edu/groups/)"
